name: C/C++ CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install_depends
      run: sudo apt-get install -y zlib1g-dev libbz2-dev liblzma-dev libcurl4-gnutls-dev libssl-dev 
    - name: Checkout submodules
      run: git clone --recurse-submodules https://github.com/samtools/htslib.git
    - name: autoheader
      run: autoheader
    - name: autoconf
      run: autoconf
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
